# Generated by Django 6.0.1 on 2026-02-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='title_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
