# Generated by Django 6.0.1 on 2026-02-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_feature_title_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='bg_title_color',
            field=models.CharField(blank=True, default='#008000', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20),
        ),
    ]
