# Generated by Django 6.0.1 on 2026-02-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
