# Generated by Django 6.0.1 on 2026-04-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productvariant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='featured_list', to='products.feature'),
        ),
    ]
