# Generated by Django 6.0.1 on 2026-04-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_features_productvariant_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='variants', to='products.feature'),
        ),
    ]
