# Generated by Django 6.0.1 on 2026-02-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
