# Generated by Django 6.0.1 on 2026-02-07 07:59

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_served_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, related_name='order_items', to='orders.order'),
        ),
    ]
