# Generated by Django 6.0.1 on 2026-02-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
