# Generated by Django 6.0.1 on 2026-06-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerlocation_city_customerlocation_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('client', 'client'), ('vendor', 'vendor')], default='client', max_length=10),
        ),
    ]
