# Generated by Django 6.0.1 on 2026-06-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendorprofile_created_by_vendorprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
