# Generated by Django 6.0.1 on 2026-06-01 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vendorprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='location',
            new_name='business_location',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='phone',
            new_name='business_phone',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='status',
            new_name='business_status',
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
