# Generated by Django 6.0.1 on 2026-06-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_location_vendorprofile_business_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='latitude',
            new_name='business_latitude',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='longitude',
            new_name='business_longitude',
        ),
    ]
