# Generated by Django 6.0.1 on 2026-02-12 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_checkout_request_id_order_merchant_request_id'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='checkout_request_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='raw_payload',
            field=models.JSONField(null=True),
        ),
    ]
