# Generated by Django 6.0.1 on 2026-02-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_mpesa_receipt_order_paid_amount_and_more'),
        ('payments', '0003_mpesapayment_result_code_mpesapayment_result_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
    ]
