# Generated by Django 6.0.1 on 2026-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesaconfig',
            name='till',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
