# Generated by Django 6.0.1 on 2026-03-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0002_mpesaconfig_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesaconfig',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
